// <auto-generated />
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    [Migration("20200415090953_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelter.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Gender");

                    b.Property<string>("Name");

                    b.Property<string>("Species");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 5,
                            Gender = "Male",
                            Name = "Max",
                            Species = "German-Shepherd"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 1,
                            Gender = "Female",
                            Name = "Lucy",
                            Species = "Showshoe"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 2,
                            Gender = "Male",
                            Name = "Bingo",
                            Species = "Persian Cat"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 3,
                            Gender = "Male",
                            Name = "Chico",
                            Species = "Bulldog"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 4,
                            Gender = "Female",
                            Name = "Camila",
                            Species = "Chihuahua"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
